version: '3.8'

services:
  # --- BACKEND SERVICES ---
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      # Maps your computer's port 4000 to the container's port 4000
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      # You can add database URLs or other secrets here
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cartdb
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cartdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d cartdb -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  shopping-cart:
    container_name: mips_shopping_cart
    build:
      context: ./MIPS-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./MIPS-frontend:/app
      - /app/node_modules

volumes:
  backend_node_modules:
  postgres_data:
