name: CI
on:
  push:
    branches: [ main, pubsub_refinements, pubsub ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --prefix backend
      - run: npx --prefix backend eslint . --ext .js,.ts,.tsx

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --prefix backend
      - run: npm run proto:build --prefix backend
      - run: npm run proto:check --prefix backend
      - run: npm --prefix MIPS-Frontend-main/mips_host ci && npm --prefix MIPS-Frontend-main/mips_host run build